"""Generate assets/stars.js from the Hipparcos main catalogue and Stellarium constellation lines.

Usage: python3 tools/build_stars.py HIP_MAIN_DAT CONSTELLATIONSHIP_FAB > assets/stars.js

hip_main.dat comes from CDS (I/239); constellationship.fab ships with skyfield's test data.
"""
import json
import sys

MAG_LIMIT = 5.6

NAMES = {
    32349: "Sirius", 30438: "Canopus", 69673: "Arcturus", 91262: "Vega", 24608: "Capella",
    24436: "Rigel", 37279: "Procyon", 27989: "Betelgeuse", 7588: "Achernar", 68702: "Hadar",
    97649: "Altair", 60718: "Acrux", 21421: "Aldebaran", 80763: "Antares", 65474: "Spica",
    37826: "Pollux", 113368: "Fomalhaut", 102098: "Deneb", 62434: "Mimosa", 49669: "Regulus",
    11767: "Polaris", 36850: "Castor", 25336: "Bellatrix", 26311: "Alnilam", 26727: "Alnitak",
    25930: "Mintaka", 27366: "Saiph", 54061: "Dubhe", 53910: "Merak", 67301: "Alkaid",
    65378: "Mizar", 85927: "Shaula", 15863: "Mirfak", 677: "Alpheratz", 14576: "Algol",
    71683: "Rigil Kentaurus",
}


def main(hip_path, fab_path):
    lines = []
    wanted = set()
    for row in open(fab_path):
        parts = row.split()
        if not parts:
            continue
        hips = [int(h) for h in parts[2:]]
        pairs = list(zip(hips[0::2], hips[1::2]))
        lines.append((parts[0], pairs))
        for a, b in pairs:
            wanted.update((a, b))

    stars = []
    for row in open(hip_path):
        f = row.split("|")
        try:
            hip, mag = int(f[1]), float(f[5])
            ra, dec = float(f[8]), float(f[9])
        except ValueError:
            continue
        if mag > MAG_LIMIT and hip not in wanted:
            continue
        try:
            bv = float(f[37])
        except ValueError:
            bv = 0.6
        stars.append((mag, hip, ra, dec, bv))
    stars.sort()

    index = {hip: i for i, (_, hip, _, _, _) in enumerate(stars)}
    packed = []
    for mag, _, ra, dec, bv in stars:
        packed += [round(ra * 20), round(dec * 20), round(mag * 10), round(bv * 100)]
    out = {
        "stars": packed,
        "names": {index[h]: n for h, n in NAMES.items() if h in index},
        "lines": {
            abbr: [i for a, b in pairs if a in index and b in index for i in (index[a], index[b])]
            for abbr, pairs in lines
        },
    }
    sys.stdout.write("// Generated by tools/build_stars.py. Hipparcos (ESA 1997), Stellarium constellation lines.\n")
    sys.stdout.write("// stars: flat [ra*20, dec*20, vmag*10, (B-V)*100] sorted by brightness.\n")
    sys.stdout.write("window.OC_SKY=" + json.dumps(out, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
